brand: Fender
subbrand: American
check_subbrand: False
min_price: 1398.99
ranges: [Stratocaster, Telecaster, Jazzmaster, Esquire, Nocaster, Jaguar, Mustang, Jazz Tele, Strat-Tele]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/fender/electric-guitars+new+solid-body-electric?page=1
