brand: PRS
alt_brand: Paul Reed Smith
subbrand: Private Stock
check_subbrand: True
ranges: [Custom 22, Custom 24]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/paul-reed-smith/electric-guitars+new+solid-body-electric?page=1
