brand: Suhr
subbrand: USA
check_subbrand: False
ranges: [Signature, Modern, Standard, Classic]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/suhr/new+electric-guitars+solid-body-electric?page=1
