brand: Gibson
subbrand: USA
check_subbrand: False
ranges: [Les Paul, SG, Firebird, Flying V, Explorer, The Paul]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/gibson/new+electric-guitars+solid-body-electric?page=1
