brand: Ernie Ball
subbrand: Music Man
check_subbrand: False
ranges: [Petrucci, St. Vincent, Cutlass, Stingray, Valentine, Steve Lukather, Steve Morse, Albert Lee, Axis, Silhouette, Armada]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/ernie-ball-music-man/new+electric-guitars+solid-body-electric?page=1
