brand: PRS
alt_brand: Paul Reed Smith
subbrand: Core
check_subbrand: False
min_price: 3000
max_price: 6000
ranges: [Custom 22, Custom 24, McCarty, Tremonti]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/paul-reed-smith/electric-guitars+new+solid-body-electric?page=1
