brand: PRS
alt_brand: Paul Reed Smith
subbrand: SE
check_subbrand: True
ranges: [Custom 24, Custom 22, Standard 24, SE 245, SE 277, SVN, Santana, Tremonti, Myers, Holcomb]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/paul-reed-smith/electric-guitars+new+solid-body-electric?page=1
