brand: PRS
alt_brand: Paul Reed Smith
subbrand: Bolt-On
check_subbrand: False
ranges: [CE 24, Silver Sky]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/paul-reed-smith/electric-guitars+new+solid-body-electric?page=1
