brand: Fender
subbrand: Custom Shop
check_subbrand: True
ranges: [Stratocaster, Telecaster, Jazzmaster, Esquire, Nocaster, Jaguar]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/fender-custom-shop/electric-guitars+new+solid-body-electric?page=1
