brand: Gibson
subbrand: Custom Shop
check_subbrand: True
ranges: [Les Paul, SG, Firebird]
year: 2018
store: themusiczoo
url: https://www.themusiczoo.com/collections/gibson-custom-shop/new+solid-body-electric?page=1
